baseurl = "http://manetteneighborhoodcoalition.org/gardentour/"
title = "Manette Edible Garden Tour"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "This is the description of the garden tour!"
  copyright = "&copy;2018 <a href='http://manetteneighborhoodcoalition.org'>Manette Neighborhood Coalition</a>"
  sidebarAbout = [
    "<h3 style='color:white'>August 4th, 2018</h3>",
    "<h4 style='color:white'>10:00am - 2:00pm</h4>",
    "<h4 style='color:white'>Check in at Discovery Fellowship</h4>",
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  # email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "About"
  url = "about/"
  home = true

  [[params.navlinks]]
  name = "Gardens"
  url = "gardens/"

  [[params.navlinks]]
  name = "Map"
  url = "map/"

  [[params.navlinks]]
  name = "Garden Resources"
  url = "garden-resources/"

  [[params.navlinks]]
  name = "Chicken Resources"
  url = "chicken-resources/"

  [params.social]
  facebook      = "https://www.facebook.com/pages/Manette-Edible-Garden-Tour/554597181267282"
  #googleplus    = "full profile url in googleplus"
  email         = "manetteediblegardens@gmail.com"
  #twitter       = "full profile url in twitter"
  #linkedin      = "full profile url in linkedin"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  #github        = "full profile url in github"
